global:
  scrape_interval: 15s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager.prodwatch.svc.cluster.local:9093"]

scrape_configs:
  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service.prodwatch.svc.cluster.local:8000"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service.prodwatch.svc.cluster.local:8001"]
